[project]
name = "HexFold"
version = "0.1.0"
description = "Student project as part of the Creative Coding course"
readme = "README.md"
requires-python = ">=3.10.0"
dependencies = [
  "py5==0.10.7a0",
]
